doctrine:
    dbal:
        default_connection: pgsql
        connections:
           
            pgsql:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_pgsql'
                ##server_version: '9.3'

    orm:
        default_entity_manager: pgsql
        entity_managers:
          
            pgsql:
                connection: pgsql
                mappings:
                    pgsql:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: pgsql